sudo: required
language: python
python:
- '3.6'
branches:
  except:
  - gh-pages
  - metadata
before_install:
- chmod +x ./*.py
- chmod +x ./*.sh
- sudo mkdir -p /mnt/lineage
- rm -rf ./metadata/ ./releases/
- rm -f ./flags.sh
install:
- ./install-brotli.sh
- sudo apt-get install -y jshon shellcheck
- pip3 install -q -r requirements.txt
before_script:
- brotli --version
- shellcheck ./pre-deploy.sh
script:
- ./los_extractor.py
- brotli --decompress --force --verbose --output=system.new.dat system.new.dat.br
- ./sdat2img.py
- sudo mount -t ext4 system.img /mnt/lineage
- ./copy_files.py
- chmod +x ./flags.sh
- source ./flags.sh
- ./pre-deploy.sh
- cat Release_Notes.md
before_deploy:
- export RELEASE_BODY=$(jshon -s "$(cat Release_Notes.md)"))
deploy:
- provider: pages
  skip_cleanup: true
  deployment-file: false
  local-dir: metadata
  skip-cleanup: true
  keep-history: true
  target-branch: metadata
  email: ${GH_EMAIL}
  name: valarie-ci-bot
  github-token: ${GH_TOKEN}
  on:
    branch: master
    condition: DEPLOY = true
- provider: release
  api_key: ${GH_TOKEN}
  file_glob: true
  file: releases/*
  skip_cleanup: true
  prerelease: true
  name: ${TRAVIS_TAG}
  body: ${RELEASE_BODY}
  overwrite: true
  on:
    branch: master
    condition: DEPLOY = true
notifications:
  email: false