sudo: required
language: python
python:
- '3.6'
branches:
  except:
  - gh-pages
  - metadata
  - 15.1.*.*
  - 16.0.*.*
  - 16.1.*.*
  - 17.0.*.*
before_install:
- chmod +x ./*.py
- chmod +x ./*.sh
- sudo mkdir -p /mnt/lineage
- rm -rf ./metadata/ ./releases/
- rm -f ./flags.sh
- git clone --branch=gh-pages    https://github.com/tprasadtp/lineageos-apk-extractor gh-pages 2>&1 > /dev/null
install:
- ./install-brotli.sh
- sudo apt-get install -y jshon shellcheck
- pip3 install -q -r requirements.txt
before_script:
- brotli --version
- shellcheck ./pre-deploy.sh
script:
- ./los_extractor.py
- brotli --decompress --force --verbose --output=system.new.dat system.new.dat.br
- ./sdat2img.py
- sudo mount -t ext4 system.img /mnt/lineage
- ./copy_files.py
- chmod +x ./flags.sh
- source ./flags.sh
before_deploy:
- ./pre-deploy.sh
- export DATE="$(date)"
deploy:
- provider: pages
  skip_cleanup: true
  deployment-file: false
  allow-empty-commit: true
  local-dir: gh-deploy
  keep-history: true
  target-branch: gh-pages
  email: ${GH_EMAIL}
  name: Valarie-CI-Bot
  github-token: ${GH_TOKEN}
  on:
    branch: master
- provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file: releases/*
  skip_cleanup: true
  prerelease: true
  name: Lineage - ${BUILD_TAG}
  body: Automatically released on ${DATE}. For [Release Notes](https://github.com/tprasadtp/lineageos-apk-extractor/tree/gh-pages/release-notes) see [here](https://github.com/tprasadtp/lineageos-apk-extractor/tree/gh-pages/release-notes/Release-Notes-${BUILD_TAG}.md). Logs can be found [here](https://github.com/tprasadtp/lineageos-apk-extractor/tree/gh-pages/release-logs/LOS_APK_Extractor-${BUILD_TAG}.log). Non taggeed logs can be found at [here](https://github.com/tprasadtp/lineageos-apk-extractor/tree/gh-pages/release-notes/Release-Notes-${BUILD_TAG}.md). Logs can be found [here](https://github.com/tprasadtp/lineageos-apk-extractor/tree/gh-pages/logs)
  overwrite: true
  on:
    branch: master
    condition: ${DEPLOY} = true
notifications:
  email: false