sudo: required
language: python
python:
- '3.6'
env:
  - LOS_DEVICE_CODENAME=bullhead
  - LOS_DEVICE_CODENAME=hammerhead
branches:
  except:
  - gh-pages
  - metadata
  - 15.1.*.*
  - 16.0.*.*
  - 16.1.*.*
  - 17.0.*.*
  - 14.*.*
  - /^untagged/
before_install:
# Lets not break build if script is not executable.
- chmod +x ./*.py ./*.sh
- sudo mkdir -p /mnt/lineage
- rm -rf ./metadata/ ./releases/ ./flags.sh
- git clone --branch=gh-pages    https://github.com/tprasadtp/lineageos-apk-extractor gh-pages 2>&1 > /dev/null
install:
# Keep for now. As soon as Travis updates to xenial, use apt-get.
- ./install-brotli.sh
- pip3 install -q -r requirements.txt
before_script:
- brotli --version
script:
- ./los_extractor.py
- ./brotli-decompress.sh
- ./sdat2img.py
- sudo mount -t ext4 system.img /mnt/lineage
- ./copy_files.py
# We need to source flags prior to "before_deploy"
- chmod +x ./flags.sh && source ./flags.sh
before_deploy:
# Git Tag, Copy logs, copy metadata files
- ./pre-deploy.sh
- export TRAVIS_TAG="${BUILD_TAG}"
deploy:
- provider: pages
  skip_cleanup: true
  deployment-file: false
  allow-empty-commit: true
  local-dir: gh-deploy
  keep-history: true
  target-branch: gh-pages
  fqdn: apk.prasadt.com
  email: ${GH_EMAIL}
  name: Valarie-CI-Bot
  github-token: ${GH_TOKEN}
  on:
    branch: master
- provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file: releases/*
  skip_cleanup: true
  prerelease: true
  name: Lineage - ${BUILD_TAG}
  body: Automatically released. Build is ${TRAVIS_BUILD_NUMBER}. For [Release Notes](https://github.com/tprasadtp/lineageos-apk-extractor/tree/gh-pages/release-notes) see [here](https://github.com/tprasadtp/lineageos-apk-extractor/tree/gh-pages/release-notes/Release-Notes-${BUILD_TAG}.md). Logs can be found [here](https://github.com/tprasadtp/lineageos-apk-extractor/tree/gh-pages/release-logs/LOS_APK_Extractor-${BUILD_TAG}.log). Non tagged logs can be found [here](https://github.com/tprasadtp/lineageos-apk-extractor/tree/gh-pages/logs).
  overwrite: true
  on:
    branch: master
    condition: ${DEPLOY} = true
notifications:
  email: false
