sudo: required
language: python
python:
- '3.6'
branches:
  except:
  - gh-pages
  - metadata
before_install:
- chmod +x ./*.py
- chmod +x ./*.sh
- sudo mkdir -p /mnt/lineage
- rm -rf ./Metadata/ ./Releases/
- rm -f ./flags.sh
install:
- sudo apt-get install -y jshon shellcheck
- pip3 install -q -r requirements.txt
script:
- ./los_extractor.py
- ./sdat2img.py system.transfer.list system.new.dat.br system.img
- echo "Mounting Image"
- sudo mount system.img /mnt/lineage
- ./copy_files.py
- chmod +x ./flags.sh && source ./flags.sh
before_deploy:
- shellcheck ./pre-deploy.sh
- ./pre-deploy.sh
- export RELEASE_BODY=$(jshon -s "$(cat Release_Notes.md)"))
deploy:
- provider: pages
  skip_cleanup: true
  deployment-file: false
  local-dir: Metadata
  skip-cleanup: true
  keep-history: true
  target-branch: metadata
  email: ${GH_EMAIL}
  name: valarie-ci-bot
  github-token: ${GH_TOKEN}
  on:
    branch: master
    condition: DEPLOY = true
- provider: release
  api_key: ${GH_TOKEN}
  file_glob: true
  file: Releases/*
  skip_cleanup: true
  prerelease: true
  name: ${TRAVIS_TAG}
  body: ${RELEASE_BODY}
  overwrite: true
  on:
    branch: master
    condition: DEPLOY = true
notifications:
  email: false