dist: bionic
language: python
cache: pip
os: linux
branches:
  only:
  - master
  - dev

#Use 3.6 for now
python:
- '3.6'

# Device codenames
env:
  - LOS_DEVICE_CODENAME=bullhead
  - LOS_DEVICE_CODENAME=guacamole

# install brotli
addons:
  apt:
    packages:
    - tree
    - brotli
  hosts:
  - travis.ci

before_install:
# Lets not break build if script is not executable.
- chmod +x ./*.py ./scripts/*.sh vendor/*.py

install:
# Keep for now. As soon as Travis updates to xenial, use apt-get.
- make install-all

# Ensure all directories are present
before_script:
- brotli --version
- mkdir -p build
- mkdir -p metadata
- mkdir -p releases
- sudo mkdir -p /mnt/lineage

script:
- ./los_extractor.py --device ${LOS_DEVICE_CODENAME}
# We need to source flags prior to "before_deploy"
- chmod +x ./build/flags.sh && source ./build/flags.sh
- ./scripts/extract.sh "${LOS_DEVICE_CODENAME}"
before_deploy:
# Git Tag, Copy logs, copy metadata files
- source ./scripts/pre-deploy.sh
# Set Git config
- source ./scripts/set-git-config.sh
# Metadata to pages
deploy:
- provider: pages
  deployment_file: false
  verbose: true
  local_dir: metadata
  cleanup: false
  keep_history: true
  commit_message: release ${TRAVIS_COMMIT:0:7} for LineageOS ${BUILD_TAG}
  target_branch: gh-pages
  token: ${GH_TOKEN}
  on:
    branch: master
    condition: ${DEPLOY} = true
  edge: true

- provider: releases
  token: ${GH_TOKEN}
  file_glob: true
  file: releases/*
  cleanup: false
  name: LineageOS - ${BUILD_TAG}
  release_notes_file: build/Release-Notes.md
  overwrite: true
  edge: true
  on:
    branch: master
    condition: ${DEPLOY} = true

# no notify
notifications:
  email: false
