# Dependabot Config
---
version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    default_labels:
      - "Actor: Dependabot"
      - "Type: Dependencies"
      - "Deps: Python"
    # automerged_updates:
    #   - match:
    #       update_type: "semver:patch"
    commit_message:
      prefix: "chore"
      include_scope: true
    version_requirement_updates: "auto"
